### PR TITLE
Fix integer underflow

### PR DESCRIPTION
**Pull request by nomis**

### CODE REVIEW

**Review by swewanroberts — APPROVED** [review]

**Comment by toddr** [comment]
If this is fixing a CVE, could we also have an official release?

**Comment by nomis** [comment]
It would be useful if someone could work out if this fixes a vulnerability or not, and then ask ZDI if it's the same issue.

**Comment by HeikoSchlittermann** [comment]
Unfortunately I still do not have any response from ZDI about this issue they filed against Exim.

**Comment by toddr** [comment]
@HeikoSchlittermann did you find you needed to ammend this patch?

**Comment by toddr** [comment]
@shevek thanks for the merge. Heiko has been experimenting with this and also added this to the patch: https://gitea.schlittermann.de/DEB/libspf2/commit/d2595c160dc62e25bfb28f4eaa2b71f3294e4fb5

Which essentially seems to be this to your branch?
```diff
+--- a/src/libspf2/spf_compile.c
++++ b/src/libspf2/spf_compile.c
+@@ -455,7 +455,11 @@
                        /* Magic numbers for x/Nc in gdb. */                                    \
                        data->ds.__unused0 = 0xba; data->ds.__unused1 = 0xbe;   \
                        dst = SPF_data_str( data );                                                             \
@@ -23,4 +12,3 @@ index b08ffe2..d401028 100644
 +                      ds_avail = (_avail) - sizeof(SPF_data_t);                               \
                        ds_len = 0;                                                                                             \
                } while(0)
```

**Comment by HeikoSchlittermann** [comment]
Maybe I'm wrong. In my *first* version I made a mistake applying @nomis' patch. Now the resulting [patch](https://gitea.schlittermann.de/DEB/libspf2/src/branch/debian/bookworm/debian/patches/integer-underflow) should be identically to the change @nomis requested in his PR.

**Pull request merged**
